homeassistant:
  name: My Smart Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 179
  unit_system: metric
  time_zone: Europe/Kiev
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages
    

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace:
  mode: yaml


hacs:
  token: !secret HACS_github
  appdaemon: true
  python_script: true
  theme: true

# Text to speech
tts:
  - platform: google_translate
  
mqtt:
#   broker: core-mosquitto  # Локальный брокер
  broker: 192.168.0.71   # Внешний брокер
  discovery: true
  discovery_prefix: homeassistant  
  username: mqtt
  password: mqtt

#Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include includes/groups.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
yeelight: !include includes/yeelight.yaml
light: !include includes/light.yaml
fan: !include includes/fan.yaml
air_quality: !include includes/air_quality.yaml
remote: !include includes/remote.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
switch: !include_dir_merge_list includes/switches
script: !include_dir_merge_named includes/scripts
binary_sensor: !include_dir_merge_list includes/bin_sensor

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - mac: F0:B4:29:CC:1F:11
      key: !secret gateway1_api
      host: 192.168.0.80
    - mac: 28:6C:07:F0:AD:27
      key: !secret gateway2_api
      host: 192.168.0.81
    - mac: 34:CE:00:88:B0:39
      key: !secret gateway3_api
      host: 192.168.0.82
    - mac: 78:11:DC:64:F4:C8
      key: !secret gateway4_api
      host: 192.168.0.83